name: Deploy 6amMart to Production

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Laravel Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/6ammart/backend

            # Pull latest changes
            git pull origin main

            # Install/update dependencies
            sudo -u www-data composer install --no-dev --optimize-autoloader --no-interaction

            # Run migrations
            sudo -u www-data php artisan migrate --force

            # Clear and cache config
            sudo -u www-data php artisan config:clear
            sudo -u www-data php artisan cache:clear
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache

            # Restart services
            sudo systemctl restart php8.2-fpm
            sudo supervisorctl restart 6ammart-worker:*

  deploy-frontend:
    name: Deploy Flutter Web
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Build Flutter web
        run: |
          cd "6mamart-3.4-Momux-in-Mehedi/Main-6ammart-3.4-Momux/Main/User app and web"
          flutter pub get
          flutter build web --release --web-renderer html

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "6mamart-3.4-Momux-in-Mehedi/Main-6ammart-3.4-Momux/Main/User app and web/build/web/*"
          target: "/tmp/flutter-build"
          strip_components: 7

      - name: Move files to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/6ammart/frontend/*
            sudo mv /tmp/flutter-build/* /var/www/6ammart/frontend/
            sudo chown -R www-data:www-data /var/www/6ammart/frontend
            sudo systemctl reload nginx

  notify:
    name: Send Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always()

    steps:
      - name: Notify on success
        if: ${{ needs.deploy-backend.result == 'success' && needs.deploy-frontend.result == 'success' }}
        run: |
          echo "✅ Deployment successful!"
          # Add notification logic (Slack, Discord, Email, etc.)

      - name: Notify on failure
        if: ${{ needs.deploy-backend.result == 'failure' || needs.deploy-frontend.result == 'failure' }}
        run: |
          echo "❌ Deployment failed!"
          exit 1
