/**
 * PM2 Ecosystem Configuration
 * Manages all backend microservices
 *
 * Usage:
 *   pm2 start ecosystem.config.js
 *   pm2 reload ecosystem.config.js
 *   pm2 stop ecosystem.config.js
 *   pm2 delete ecosystem.config.js
 */

module.exports = {
  apps: [
    // Core Services
    {
      name: 'user-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/user-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        JWT_SECRET: 'your-jwt-secret-change-this',
      },
      error_file: '/var/log/delivery-platform/user-service-error.log',
      out_file: '/var/log/delivery-platform/user-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },

    {
      name: 'restaurant-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/restaurant-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        ELASTICSEARCH_URL: 'http://localhost:9200',
      },
      error_file: '/var/log/delivery-platform/restaurant-service-error.log',
      out_file: '/var/log/delivery-platform/restaurant-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },

    {
      name: 'order-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/order-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        KAFKA_BROKERS: 'localhost:9092',
      },
      error_file: '/var/log/delivery-platform/order-service-error.log',
      out_file: '/var/log/delivery-platform/order-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },

    {
      name: 'delivery-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/delivery-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        GOOGLE_MAPS_API_KEY: 'your-google-maps-api-key',
      },
      error_file: '/var/log/delivery-platform/delivery-service-error.log',
      out_file: '/var/log/delivery-platform/delivery-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },

    {
      name: 'payment-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/payment-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        STRIPE_SECRET_KEY: 'your-stripe-secret-key',
        STRIPE_WEBHOOK_SECRET: 'your-stripe-webhook-secret',
      },
      error_file: '/var/log/delivery-platform/payment-service-error.log',
      out_file: '/var/log/delivery-platform/payment-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },

    {
      name: 'notification-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/notification-service',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        TWILIO_ACCOUNT_SID: 'your-twilio-account-sid',
        TWILIO_AUTH_TOKEN: 'your-twilio-auth-token',
        SENDGRID_API_KEY: 'your-sendgrid-api-key',
        FCM_SERVER_KEY: 'your-fcm-server-key',
      },
      error_file: '/var/log/delivery-platform/notification-service-error.log',
      out_file: '/var/log/delivery-platform/notification-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '300M',
    },

    {
      name: 'search-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/search-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3007,
        ELASTICSEARCH_URL: 'http://localhost:9200',
        REDIS_URL: 'redis://localhost:6379',
      },
      error_file: '/var/log/delivery-platform/search-service-error.log',
      out_file: '/var/log/delivery-platform/search-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '400M',
    },

    // Advanced Services
    {
      name: 'pricing-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/pricing-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3008,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        WEATHER_API_KEY: 'your-openweathermap-api-key',
      },
      error_file: '/var/log/delivery-platform/pricing-service-error.log',
      out_file: '/var/log/delivery-platform/pricing-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '400M',
    },

    {
      name: 'route-optimization-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/route-optimization-service',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3009,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        GOOGLE_MAPS_API_KEY: 'your-google-maps-api-key',
      },
      error_file: '/var/log/delivery-platform/route-optimization-service-error.log',
      out_file: '/var/log/delivery-platform/route-optimization-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '400M',
    },

    {
      name: 'fraud-detection-service',
      script: 'dist/index.js',
      cwd: '/var/www/delivery-platform/backend/services/fraud-detection-service',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3010,
        DATABASE_URL: 'postgresql://delivery_user:password@localhost:5432/delivery_platform',
        REDIS_URL: 'redis://localhost:6379',
        KAFKA_BROKERS: 'localhost:9092',
      },
      error_file: '/var/log/delivery-platform/fraud-detection-service-error.log',
      out_file: '/var/log/delivery-platform/fraud-detection-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '400M',
    },

    // AI Service
    {
      name: 'ai-recommendation-service',
      script: 'src/app.py',
      cwd: '/var/www/delivery-platform/backend/ai-services/recommendation-service',
      interpreter: 'python3',
      instances: 1,
      exec_mode: 'fork',
      env: {
        FLASK_ENV: 'production',
        PORT: 5000,
        REDIS_URL: 'redis://localhost:6379',
        MODEL_PATH: '/var/www/delivery-platform/backend/ai-services/recommendation-service/models',
      },
      error_file: '/var/log/delivery-platform/ai-recommendation-service-error.log',
      out_file: '/var/log/delivery-platform/ai-recommendation-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
  ],

  /**
   * Deployment configuration
   */
  deploy: {
    production: {
      user: 'ubuntu',
      host: '52.66.71.133',
      ref: 'origin/main',
      repo: 'git@github.com:yourusername/delivery-platform.git',
      path: '/var/www/delivery-platform',
      'post-deploy': 'npm install && npm run build && pm2 reload ecosystem.config.js --env production',
      env: {
        NODE_ENV: 'production',
      },
    },
  },
};
